"""added v1 medical report v1 name error

Revision ID: 1d7b333a07da
Revises: 8b58c228c7b7
Create Date: 2025-10-01 11:17:29.263837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7b333a07da'
down_revision: Union[str, None] = '8b58c228c7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
