"""added v1 medical report table

Revision ID: 8b58c228c7b7
Revises: c9be85d3574f
Create Date: 2025-10-01 11:15:37.877266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b58c228c7b7'
down_revision: Union[str, None] = 'c9be85d3574f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_reports_v1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_report', sa.String(), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_reports_v1_id'), 'medical_reports_v1', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_reports_v1_id'), table_name='medical_reports_v1')
    op.drop_table('medical_reports_v1')
    # ### end Alembic commands ###
