"""Add fhir table

Revision ID: 96f5233be90f
Revises: ef8c2d119c5c
Create Date: 2025-09-23 13:48:15.731019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f5233be90f'
down_revision: Union[str, None] = 'ef8c2d119c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fhir_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fhir_bundle', sa.String(), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fhir_bundles_id'), 'fhir_bundles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fhir_bundles_id'), table_name='fhir_bundles')
    op.drop_table('fhir_bundles')
    # ### end Alembic commands ###
