"""Add transcript_id to NRCES bundles

Revision ID: a3f2aab691f6
Revises: f2226b4ff191
Create Date: 2025-12-18 12:06:24.193010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f2aab691f6'
down_revision: Union[str, None] = 'f2226b4ff191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostic_report_bundles', sa.Column('transcript_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diagnostic_report_bundles', 'transcripts', ['transcript_id'], ['id'])
    op.add_column('discharge_summary_bundles', sa.Column('transcript_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'discharge_summary_bundles', 'transcripts', ['transcript_id'], ['id'])
    op.add_column('immunization_bundles', sa.Column('transcript_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'immunization_bundles', 'transcripts', ['transcript_id'], ['id'])
    op.add_column('op_consult_bundles', sa.Column('transcript_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'op_consult_bundles', 'transcripts', ['transcript_id'], ['id'])
    op.add_column('prescription_bundles', sa.Column('transcript_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prescription_bundles', 'transcripts', ['transcript_id'], ['id'])
    op.add_column('wellness_bundles', sa.Column('transcript_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wellness_bundles', 'transcripts', ['transcript_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wellness_bundles', type_='foreignkey')
    op.drop_column('wellness_bundles', 'transcript_id')
    op.drop_constraint(None, 'prescription_bundles', type_='foreignkey')
    op.drop_column('prescription_bundles', 'transcript_id')
    op.drop_constraint(None, 'op_consult_bundles', type_='foreignkey')
    op.drop_column('op_consult_bundles', 'transcript_id')
    op.drop_constraint(None, 'immunization_bundles', type_='foreignkey')
    op.drop_column('immunization_bundles', 'transcript_id')
    op.drop_constraint(None, 'discharge_summary_bundles', type_='foreignkey')
    op.drop_column('discharge_summary_bundles', 'transcript_id')
    op.drop_constraint(None, 'diagnostic_report_bundles', type_='foreignkey')
    op.drop_column('diagnostic_report_bundles', 'transcript_id')
    # ### end Alembic commands ###
