"""fhir string to json

Revision ID: c9be85d3574f
Revises: 96f5233be90f
Create Date: 2025-09-29 04:36:51.443413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Import the PostgreSQL specific JSON/JSONB type for clarity
from sqlalchemy.dialects import postgresql 


# revision identifiers, used by Alembic.
revision: str = 'c9be85d3574f'
down_revision: Union[str, None] = '96f5233be90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fhir_bundles', 'fhir_bundle',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()), # Using JSONB is generally better for performance
               existing_nullable=True,
               # 🌟 THE CRITICAL CHANGE: Explicitly tell PostgreSQL to cast the string to JSON
               postgresql_using='fhir_bundle::jsonb' 
               # Note: If you used sa.JSON(), you'd use 'fhir_bundle::json'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fhir_bundles', 'fhir_bundle',
               existing_type=postgresql.JSONB(astext_type=sa.Text()), # Match the type used in upgrade
               type_=sa.VARCHAR(),
               existing_nullable=True,
               # OPTIONAL: Explicit cast for downgrade
               postgresql_using='CAST(fhir_bundle AS VARCHAR)'
    )
    # ### end Alembic commands ###