"""added nrces bundles tables

Revision ID: f2226b4ff191
Revises: b2c7be11f910
Create Date: 2025-12-18 10:10:15.481686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2226b4ff191'
down_revision: Union[str, None] = 'b2c7be11f910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_report_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('bundle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_report_bundles_bundle_id'), 'diagnostic_report_bundles', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_diagnostic_report_bundles_id'), 'diagnostic_report_bundles', ['id'], unique=False)
    op.create_table('discharge_summary_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('bundle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discharge_summary_bundles_bundle_id'), 'discharge_summary_bundles', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_discharge_summary_bundles_id'), 'discharge_summary_bundles', ['id'], unique=False)
    op.create_table('immunization_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('bundle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immunization_bundles_bundle_id'), 'immunization_bundles', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_immunization_bundles_id'), 'immunization_bundles', ['id'], unique=False)
    op.create_table('op_consult_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('bundle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_consult_bundles_bundle_id'), 'op_consult_bundles', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_op_consult_bundles_id'), 'op_consult_bundles', ['id'], unique=False)
    op.create_table('prescription_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('bundle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_bundles_bundle_id'), 'prescription_bundles', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_prescription_bundles_id'), 'prescription_bundles', ['id'], unique=False)
    op.create_table('wellness_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(), nullable=True),
    sa.Column('bundle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_bundles_bundle_id'), 'wellness_bundles', ['bundle_id'], unique=True)
    op.create_index(op.f('ix_wellness_bundles_id'), 'wellness_bundles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellness_bundles_id'), table_name='wellness_bundles')
    op.drop_index(op.f('ix_wellness_bundles_bundle_id'), table_name='wellness_bundles')
    op.drop_table('wellness_bundles')
    op.drop_index(op.f('ix_prescription_bundles_id'), table_name='prescription_bundles')
    op.drop_index(op.f('ix_prescription_bundles_bundle_id'), table_name='prescription_bundles')
    op.drop_table('prescription_bundles')
    op.drop_index(op.f('ix_op_consult_bundles_id'), table_name='op_consult_bundles')
    op.drop_index(op.f('ix_op_consult_bundles_bundle_id'), table_name='op_consult_bundles')
    op.drop_table('op_consult_bundles')
    op.drop_index(op.f('ix_immunization_bundles_id'), table_name='immunization_bundles')
    op.drop_index(op.f('ix_immunization_bundles_bundle_id'), table_name='immunization_bundles')
    op.drop_table('immunization_bundles')
    op.drop_index(op.f('ix_discharge_summary_bundles_id'), table_name='discharge_summary_bundles')
    op.drop_index(op.f('ix_discharge_summary_bundles_bundle_id'), table_name='discharge_summary_bundles')
    op.drop_table('discharge_summary_bundles')
    op.drop_index(op.f('ix_diagnostic_report_bundles_id'), table_name='diagnostic_report_bundles')
    op.drop_index(op.f('ix_diagnostic_report_bundles_bundle_id'), table_name='diagnostic_report_bundles')
    op.drop_table('diagnostic_report_bundles')
    # ### end Alembic commands ###
